[project]
<<<<<<< HEAD
name = "todo-cli"
=======
name = "unit-converter"
>>>>>>> 6c19231 (Initial commit)
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
<<<<<<< HEAD
    "click>=8.1.8",
=======
    "streamlit>=1.42.2",
>>>>>>> 6c19231 (Initial commit)
]
